
assert(load(Base64Decode("G0x1YVIAAQQEBAgAGZMNChoKAAAAAAAAAAAAAQIKAAAABgBAAEFAAAAdQAABBkBAAGUAAAAKQACBBkBAAGVAAAAKQICBHwCAAAQAAAAEBgAAAGNsYXNzAAQNAAAAU2NyaXB0U3RhdHVzAAQHAAAAX19pbml0AAQLAAAAU2VuZFVwZGF0ZQACAAAAAgAAAAgAAAACAAotAAAAhkBAAMaAQAAGwUAABwFBAkFBAQAdgQABRsFAAEcBwQKBgQEAXYEAAYbBQACHAUEDwcEBAJ2BAAHGwUAAxwHBAwECAgDdgQABBsJAAAcCQQRBQgIAHYIAARYBAgLdAAABnYAAAAqAAIAKQACFhgBDAMHAAgCdgAABCoCAhQqAw4aGAEQAx8BCAMfAwwHdAIAAnYAAAAqAgIeMQEQAAYEEAJ1AgAGGwEQA5QAAAJ1AAAEfAIAAFAAAAAQFAAAAaHdpZAAEDQAAAEJhc2U2NEVuY29kZQAECQAAAHRvc3RyaW5nAAQDAAAAb3MABAcAAABnZXRlbnYABBUAAABQUk9DRVNTT1JfSURFTlRJRklFUgAECQAAAFVTRVJOQU1FAAQNAAAAQ09NUFVURVJOQU1FAAQQAAAAUFJPQ0VTU09SX0xFVkVMAAQTAAAAUFJPQ0VTU09SX1JFVklTSU9OAAQEAAAAS2V5AAQHAAAAc29ja2V0AAQIAAAAcmVxdWlyZQAECgAAAGdhbWVTdGF0ZQAABAQAAAB0Y3AABAcAAABhc3NlcnQABAsAAABTZW5kVXBkYXRlAAMAAAAAAADwPwQUAAAAQWRkQnVnc3BsYXRDYWxsYmFjawABAAAACAAAAAgAAAAAAAMFAAAABQAAAAwAQACBQAAAHUCAAR8AgAACAAAABAsAAABTZW5kVXBkYXRlAAMAAAAAAAAAQAAAAAABAAAAAQAQAAAAQG9iZnVzY2F0ZWQubHVhAAUAAAAIAAAACAAAAAgAAAAIAAAACAAAAAAAAAABAAAABQAAAHNlbGYAAQAAAAAAEAAAAEBvYmZ1c2NhdGVkLmx1YQAtAAAAAwAAAAMAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABgAAAAYAAAAGAAAABgAAAAUAAAADAAAAAwAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAHAAAABwAAAAcAAAAIAAAACAAAAAgAAAAIAAAAAgAAAAUAAABzZWxmAAAAAAAtAAAAAgAAAGEAAAAAAC0AAAABAAAABQAAAF9FTlYACQAAAA4AAAACAA0XAAAAhwBAAIxAQAEBgQAAQcEAAJ1AAAKHAEAAjABBAQFBAQBHgUEAgcEBAMcBQgABwgEAQAKAAIHCAQDGQkIAx4LCBQHDAgAWAQMCnUCAAYcAQACMAEMBnUAAAR8AgAANAAAABAQAAAB0Y3AABAgAAABjb25uZWN0AAQRAAAAc2NyaXB0c3RhdHVzLm5ldAADAAAAAAAAVEAEBQAAAHNlbmQABAsAAABHRVQgL3N5bmMtAAQEAAAAS2V5AAQCAAAALQAEBQAAAGh3aWQABAcAAABteUhlcm8ABAkAAABjaGFyTmFtZQAEJgAAACBIVFRQLzEuMA0KSG9zdDogc2NyaXB0c3RhdHVzLm5ldA0KDQoABAYAAABjbG9zZQAAAAAAAQAAAAAAEAAAAEBvYmZ1c2NhdGVkLmx1YQAXAAAACgAAAAoAAAAKAAAACgAAAAoAAAALAAAACwAAAAsAAAALAAAADAAAAAwAAAANAAAADQAAAA0AAAAOAAAADgAAAA4AAAAOAAAACwAAAA4AAAAOAAAADgAAAA4AAAACAAAABQAAAHNlbGYAAAAAABcAAAACAAAAYQAAAAAAFwAAAAEAAAAFAAAAX0VOVgABAAAAAQAQAAAAQG9iZnVzY2F0ZWQubHVhAAoAAAABAAAAAQAAAAEAAAACAAAACAAAAAIAAAAJAAAADgAAAAkAAAAOAAAAAAAAAAEAAAAFAAAAX0VOVgA="), nil, "bt", _ENV))() ScriptStatus("UHKILIKJJHN") 

function OnLoad()
	
	PrintChat ("Buzzet's Collection 1.2.1 (04.03.15) loaded")
	
	
	--Menu
	Config = scriptConfig("AutoExhaust", "bheal")
	Config:addParam("exhaust", "Auto Exhaust", SCRIPT_PARAM_ONOFF, true)
	Config:addParam("se", "HP when Exhaust will be used (%)", SCRIPT_PARAM_SLICE, 50, 0, 100, 0)
	HPHeal = scriptConfig("AutoHeal", "bheal")
	HPHeal:addParam("heal", "Auto Heal", SCRIPT_PARAM_ONOFF, true)
	HPHeal:addParam("hp", "Hp when AutoHeal will be used (%)", SCRIPT_PARAM_SLICE, 15, 0, 100, 0)
	PotConfig = scriptConfig("AutoPot", "apot")
	PotConfig:addParam("healpot", "Health Potion Use", SCRIPT_PARAM_ONOFF, true)
	PotConfig:addParam("hphealpot", "HP for Health Potion (%)", SCRIPT_PARAM_SLICE, 50, 0, 100, 0)
	ManaConfig = scriptConfig("AutoMana", "apot")
	ManaConfig:addParam("manapot", "Mana Potion Use", SCRIPT_PARAM_ONOFF, true)
	ManaConfig:addParam("mmanapot", "HP for Mana Potion (%)", SCRIPT_PARAM_SLICE, 50, 0, 100, 0)
	
	ts = TargetSelector(TARGET_MOST_AD, 650)
	
end
 
 
myHero = GetMyHero()




function OnTick() 
	
	-- Mana Potion
	if not TargetHaveBuff( "FlaskOfCrystalWater" , myHero) then
		
		if (ManaConfig.manapot) then
			
			if (myHero.mana/myHero.maxMana < ManaConfig.mmanapot/100) then
				
				CastSpell(ITEM_2)
			
			end
				
		end
			
	end
	
	
	--HP Potion
	if not TargetHaveBuff( "RegenerationPotion" , myHero) then
		if (PotConfig.healpot) then
			if (myHero.health/myHero.maxHealth < PotConfig.hphealpot/100) then
			
				
				--CastItem(2003)
				CastSpell(ITEM_1)
					
			
			end
			
		end
	
	end
	--Summoner Heal
	if (HPHeal.heal) then
		
		if (myHero.health/myHero.maxHealth < HPHeal.hp/100) then
		
			if (myHero:CanUseSpell(SUMMONER_2) == READY) then
			
				CastSpell(SUMMONER_2)
				
					
			end
			
		end
		
	end
	-- Summoner Exhaust
	ts:update()
	
	if (ts.target ~= nil) then
		
		if (ts.target.health/ts.target.maxHealth < Config.se/100) then
		
			if (Config.exhaust) then
		
				if (myHero:CanUseSpell(SUMMONER_1) == READY) then
			
					CastSpell(SUMMONER_1, ts.target)
				
				end
				
			end
		
		end	
		
	end

end
